# Generated by Django 5.1.1 on 2024-09-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatmodel',
            options={'verbose_name': 'Plat', 'verbose_name_plural': 'Plats'},
        ),
        migrations.AlterModelOptions(
            name='menumodel',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
